---
- name: Create File with Content
  hosts: all
  gather_facts: false

  tasks:
    - name: Create file with content
      copy:
        dest: /home/vagrant/file.txt
        content: |
          Hello Liran
